---
title: "Zwischen Gesellschaft und sozialem Umfeld: Einflussfaktoren der Gründungsintention bei Studierenden"
output: html_document
date: "2025-12-19"
author: "Valérie S. & Ysabelle M."
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Einleitung

Hier kommt die Einleitung hin:

- Thema (Unternehmertum bei Studierenden und Einflüsse auf die Gründungsabsichten)
- Kontext (Guesss Studie) -> evtl. Dokument verlinken? 
- Warum ist das Thema relevant (für diese Untersuchung)?


## Forschungsfrage

In dieser Untersuchung haben wir folgende Fragestellung verfolgt:  
**Welche Rolle spielt die** ***(1) individuelle Wahrnehmung gesellschaftlicher Strukturen*** **und die** ***(2) erwartete Reaktion des persönlichen Umfelds*** **in der** ***Gründungsintention*** **von** ***weiblichen und männlichen Studierenden?***

Hier folgt eine kurze Begründung zur Auswahl der Fragestellung.


## Daten & Variablen

Zur Beantwortung der Forschungsfrage wurden folgende Variablen aus dem GUESSS-Datensatz verwendet:<br>Q7.2, Q4.1.1_2, Q6.1.1_1, Q6.1.2_1, Q6.1.3_1, Q6.2_1, Q6.2_2, Q6.2_3<br><br>
**Geschlecht**  
Das Geschlecht der Befragten (Q7.2) wurde als Gruppierungsvariable verwendet, um Unterschiede zwischen weiblichen und männlichen Studierenden zu untersuchen.  

**Gründungsabsicht**  
Die Stärke der Gründungsabsicht der Studierenden wurde mit dem Item „Mein professionelles Ziel ist es, Entrepreneur zu werden“ (Q4.1.1_2) erfasst. Die Antwort erfolgte auf einer 7-stufigen Likert-Skala von 1 (stimme überhaupt nicht zu) bis 7 (stimme voll zu). Höhere Werte zeigen eine stärkere Gründungsabsicht an.  
*➝ abhängige Variable  *

**Wahrnehmung gesellschaftlicher Strukturen**  
Die individuelle Wahrnehmung gesellschaftlicher Macht- und Autoritätsstrukturen wurde mithilfe von drei Items erfasst. Diese beziehen sich darauf,\
(1) ob gesellschaftlicher Einfluss eher auf individuellen Fähigkeiten und Beiträgen oder auf formalen Positionen basiert (Q6.1.1_1),\
(2) inwieweit das Hinterfragen von Autoritäten als akzeptiert gilt (Q6.1.2_1), sowie\
(3) ob Macht in der Gesellschaft als breit verteilt oder stark konzentriert wahrgenommen wird. (Q6.1.3_1)\
Alle Items wurden auf einer 7-stufigen Skala erhoben. Die drei Items wurden zu einer Skala zusammengefasst, indem der Mittelwert gebildet wurde (aus den Einzelitems). Höhere Werte stehen für eine stärker egalitär wahrgenommene Gesellschaftsstruktur.  
*➝ unabhängige Variable  *


**Erwartete Reaktion des persönlichen Umfelds**  
Die erwartete Reaktion des persönlichen Umfelds auf eine mögliche unternehmerische Tätigkeit wurde anhand der Einschätzung der Reaktionen von Familie (Q6.2_1), Freunden (Q6.2_2) und Mitstudierenden (Q6.2_3) gemessen. Die Befragten gaben auf einer 7-stufigen Skala von 1 (sehr negativ) bis 7 (sehr positiv) an, wie sie die Reaktionen ihres Umfelds einschätzen würden. Die drei Items wurden zu einer Skala zusammengefasst, wobei höhere Werte eine positivere erwartete Reaktion des Umfelds anzeigen.  
*➝ unabhängige Variable  *


## Deskriptive Statistik

Hier folgende der Abschnitt:

- Kennwerte (Mittelwerte, Median, SD)
- Grafiken
- Kurze Interpretation (was fällt auf? was lässt sich aus der Grafik herauslesen? Z.B. Signifikanz)


## Gruppenvergleiche der Variablen

Hier folgt der Abschnitt:

- T-Test
- Wilcoxon-Test
- Interpretation der Ergebnisse


## Beziehungen zwischen den Variablen

Hier folgt der Abschnitt:

- Zusammenhänge zwischen: Umfeldreaktion vs. Gründungsabsicht, Gesellschaftswahrnehmung vs. Gründungsabsicht, Vergleich dieser Einflüsse bei Mann vs. Frau
- Interpretation


## Diskussion

Hier folgt der Abschnitt:

- Beantwortung der Forschungsfrage 
- Einordnung der Ergebnisse (z.B. warum keine signifikanten Unterschiede?)


## Reflexion & Limitationen

Hier folgt der Abschnitt:

- Stichprobe (Studierende)
- Subjektive Einschätzung
- Keine Kausalität


## Fazit

Hier folgt der Abschnitt:

- 2-3 Abschlusssätze
- Was haben wir gelernt?

